FROM nginx:1.27-alpine

# Remove default config
RUN rm /etc/nginx/conf.d/default.conf

# Copy our custom nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf

# Expose the internal port Nginx listens on
EXPOSE 80

# Nginx automatically starts when the container runs
CMD ["nginx", "-g", "daemon off;"]